language: cpp
notifications:
  email: false
sudo: false
dist: trusty
services:
- docker
matrix:
  include:
  - os: linux
    compiler: clang-5
    env: CXX=clang++-5 CC=clang-5
  - os: linux
    compiler: gcc-6
    env: CXX=g++ CC=gcc
script:
- docker run -e "CI" -e "TRAVIS" -e "TRAVIS_TAG" -e "CXX" -e "CC" --tty=false -it -v $PWD:/src --workdir /src
  bentou/ubuntu-cosmic-dev python3 ./build.py $REPOSITORY_KEY
before_script:
- docker pull bentou/ubuntu-cosmic-dev
- docker ps -a
- mkdir bin
env:
  matrix:
    secure: UdlKW8Hvt3arJNCxLQQLOvAap06xRiWmkxMkjwrdx87QJOMRxXrTHqcgUza/af/NqLUzhFxumQOmT+PIZLh+Iy6tmYQvCqR+ic1VMiCGjDit4kfTtS3MdZtJcXnKw76FL+0FXY6xo2M4sWhKVOPSJ/2Ui0PcuW/dkvIgLGHfzo1Y1SwP+tsgdWVV7Gbuo27aq/I5vZ9qwaMLHXiWRjrCunoYqwcHFJqEMTznWesj16Z1Dk09qhsSlQN4hsowgJNeX1Z6NJPZpRR+XZGhjhg0XaV0j4z8ukeBRBvb8rWnYKdXDoAI7/p/gYacMxaNsIlvfVCSAPWu0qsgrW1JUH8eqKLBz1PK/UycfDCj2ZkBcrdpeIBTijWDM6chn3qVAUSajSWWy9N56hUZSyWbIKyeqwehpLVcY1lF7k5exYtMPRiIIu2/yKDbCh99mLxEDCv6aQ44IiReUI+4au0GkOr1p8ZZSrPkfmYKqg0GekekSRHuU/m24wX7fiQi5MGL1E+0BksuH4YKWzBZkeImsDzlgCyf40jABUj+oRGTx2Ykpu6u/c5wZ7Bn1D4XMgy4quj9orZQrIwyYwUF3o99eWYEDCnznDinXUBTV+yctwZYtju6n50fgO1TyUGC2MU8k46kBzhHPCZmKm7Ta5WUu9CD7JGbn80b7FyOGMq96CVJ4Ug=
